export const Jobs = [
  {
    title: "Registered Nurse (RN)",
    link: "#",
    categ: "Bayada Home Care",
    excerpt: "Home Health Care Agency Boston, MA (Field-Based)",
    img: "/images/feature.png",
    type: "Full-time",
    hours: "40 Hours / Week",
    salary: "$75,000-$120,000",
  },
  {
    title: "Registered Nurse (RN)",
    link: "#",
    categ: "Bayada Home Care",
    excerpt: "Home Health Care Agency Boston, MA (Field-Based)",
    img: "/images/feature.png",
    type: "Full-time",
    hours: "40 Hours / Week",
    salary: "$75,000-$120,000",
  },
  {
    title: "Registered Nurse (RN)",
    link: "#",
    categ: "Bayada Home Care",
    excerpt: "Home Health Care Agency Boston, MA (Field-Based)",
    img: "/images/feature.png",
    type: "Full-time",
    hours: "40 Hours / Week",
    salary: "$75,000-$120,000",
  },
  {
    title: "Registered Nurse (RN)",
    link: "#",
    categ: "Bayada Home Care",
    excerpt: "Home Health Care Agency Boston, MA (Field-Based)",
    img: "/images/feature.png",
    type: "Full-time",
    hours: "40 Hours / Week",
    salary: "$75,000-$120,000",
  },
  {
    title: "Registered Nurse (RN)",
    link: "#",
    categ: "Bayada Home Care",
    excerpt: "Home Health Care Agency Boston, MA (Field-Based)",
    img: "/images/feature.png",
    type: "Full-time",
    hours: "40 Hours / Week",
    salary: "$75,000-$120,000",
  },
  {
    title: "Registered Nurse (RN)",
    link: "#",
    categ: "Bayada Home Care",
    excerpt: "Home Health Care Agency Boston, MA (Field-Based)",
    img: "/images/feature.png",
    type: "Full-time",
    hours: "40 Hours / Week",
    salary: "$75,000-$120,000",
  },
  {
    title: "Registered Nurse (RN)",
    link: "#",
    categ: "Bayada Home Care",
    excerpt: "Home Health Care Agency Boston, MA (Field-Based)",
    img: "/images/feature.png",
    type: "Full-time",
    hours: "40 Hours / Week",
    salary: "$75,000-$120,000",
  },
  {
    title: "Registered Nurse (RN)",
    link: "#",
    categ: "Bayada Home Care",
    excerpt: "Home Health Care Agency Boston, MA (Field-Based)",
    img: "/images/feature.png",
    type: "Full-time",
    hours: "40 Hours / Week",
    salary: "$75,000-$120,000",
  },
];
