"use client";

import {
  BuildingIcon,
  DocumentIcon,
  DocumentMagnifyIcon,
  DocumentsMinusIcon,
  HomeIcon,
  LogoutIcon,
  MessagesIcon,
  ProfileIcon,
  SettingsIcon,
  EducationIcon,
} from "@/svgs/icons";
import Discover from "@/components/Discover";
import Invites from "@/components/Invites";
import Applications from "@/components/Applications";
import trinityHealth from "../../../public/images/trinityHealth.png";
import Image from "next/image";
import feature from "../../../public/images/feature.png";
import { ClockIcon } from "@/svgs/ClockIcon";
import moment from "moment";

export const navigation = [
  {
    name: "Home",
    href: "/",
    icon: <HomeIcon className="w-5 h-5" aria-hidden="true" />,
    current: true,
  },
  {
    name: "Profile",
    href: "/profile/overview",
    icon: <ProfileIcon className="w-5 h-5" aria-hidden="true" />,
    current: false,
  },
  {
    name: "My Work",
    href: "/work/discover",
    icon: <DocumentIcon className="w-6 h-6" aria-hidden="true" />,
    current: false,
  },
  {
    name: "Messages",
    href: "/messages",
    icon: <MessagesIcon className="w-6 h-6" aria-hidden="true" />,
    current: false,
  },
  {
    name: "Employers",
    href: "/employers",
    icon: <BuildingIcon className="w-6 h-6" aria-hidden="true" />,
    current: false,
  },
  {
    name: "Settings",
    href: "/settings/notifications",
    icon: <SettingsIcon className="w-6 h-6" aria-hidden="true" />,
    current: false,
  },
  {
    name: "Log Out",
    href: "/",
    icon: <LogoutIcon className="w-6 h-6" aria-hidden="true" />,
    current: false,
  },
];

export const tabData = [
  {
    id: "discover",
    label: "Discover",
    component: <Discover />,
    icon: <DocumentMagnifyIcon className="w-5 h-5" aria-hidden="true" />,
  },
  {
    id: "invites",
    label: "Invites",
    component: <Invites />,
    icon: <DocumentsMinusIcon className="w-5 h-5" aria-hidden="true" />,
  },
  {
    id: "applications",
    label: "Applications",
    component: <Applications />,
    icon: <EducationIcon className="w-5 h-5" aria-hidden="true" />,
  },
  // {
  //   id: "joboffers",
  //   label: "Job Offers",
  //   component: <JobOffers />,
  //   icon: <BreifcaseIcon className="w-5 h-5" aria-hidden="true" />,
  // },
];

// export const discoverData = [
//   {
//     id: 1,
//     image: <Image src={trinityHealth} alt="Career Image" />,
//     title: "Registered Nurse (RN)",
//     subTitle: "Bayada Home Care",
//     description: "Home Health Care Agency Boston, MA (Field-Based)",
//     tags: ["Full Time", "40 Hours / Week", "$75,000-$120,000"],
//     progress: 80,
//   },
//   {
//     id: 2,
//     image: <Image src={trinityHealth} alt="Career Image" />,
//     title: "Registered Nurse (RN)",
//     subTitle: "Bayada Home Care",
//     description: "Home Health Care Agency Boston, MA (Field-Based)",
//     tags: ["Full Time", "40 Hours / Week", "$75,000-$120,000"],
//     progress: 60,
//   },
//   {
//     id: 3,
//     image: <Image src={trinityHealth} alt="Career Image" />,
//     title: "Registered Nurse (RN)",
//     subTitle: "Bayada Home Care",
//     description: "Home Health Care Agency Boston, MA (Field-Based)",
//     tags: ["Full Time", "40 Hours / Week", "$75,000-$120,000"],
//     progress: 40,
//   },
//   {
//     id: 4,
//     image: <Image src={trinityHealth} alt="Career Image" />,
//     title: "Registered Nurse (RN)",
//     subTitle: "Bayada Home Care",
//     description: "Home Health Care Agency Boston, MA (Field-Based)",
//     tags: ["Full Time", "40 Hours / Week", "$75,000-$120,000"],
//     progress: 40,
//   },
//   {
//     id: 5,
//     image: <Image src={trinityHealth} alt="Career Image" />,
//     title: "Registered Nurse (RN)",
//     subTitle: "Bayada Home Care",
//     description: "Home Health Care Agency Boston, MA (Field-Based)",
//     tags: ["Full Time", "40 Hours / Week", "$75,000-$120,000"],
//     progress: 40,
//   },
//   {
//     id: 6,
//     image: <Image src={trinityHealth} alt="Career Image" />,
//     title: "Registered Nurse (RN)",
//     subTitle: "Bayada Home Care",
//     description: "Home Health Care Agency Boston, MA (Field-Based)",
//     tags: ["Full Time", "40 Hours / Week", "$75,000-$120,000"],
//     progress: 40,
//   },
// ];
// export const invitesData = [
//   {
//     id: 1,
//     invitation: "toApply",
//     image: <Image src={trinityHealth} alt="Career Image" />,
//     title: "Registered Nurse (RN)",
//     subTitle: "Bayada Home Care",
//     description: "Home Health Care Agency Boston, MA (Field-Based)",
//     tags: ["Full Time", "40 Hours / Week", "$75,000-$120,000"],
//     progress: 80,
//   },
//   {
//     id: 2,
//     invitation: "declined",
//     image: <Image src={trinityHealth} alt="Career Image" />,
//     title: "Registered Nurse (RN)",
//     subTitle: "Bayada Home Care",
//     description: "Home Health Care Agency Boston, MA (Field-Based)",
//     tags: ["Full Time", "40 Hours / Week", "$75,000-$120,000"],
//     progress: 60,
//   },
//   {
//     id: 3,
//     invitation: "alreadyDeclined",
//     image: <Image src={trinityHealth} alt="Career Image" />,
//     title: "Registered Nurse (RN)",
//     subTitle: "Bayada Home Care",
//     description: "Home Health Care Agency Boston, MA (Field-Based)",
//     tags: ["Full Time", "40 Hours / Week", "$75,000-$120,000"],
//     progress: 40,
//   },
//   {
//     id: 4,
//     invitation: "accepted",
//     image: <Image src={trinityHealth} alt="Career Image" />,
//     title: "Registered Nurse (RN)",
//     subTitle: "Bayada Home Care",
//     description: "Home Health Care Agency Boston, MA (Field-Based)",
//     tags: ["Full Time", "40 Hours / Week", "$75,000-$120,000"],
//     progress: 40,
//   },
//   {
//     id: 5,
//     invitation: "declined",
//     image: <Image src={trinityHealth} alt="Career Image" />,
//     title: "Registered Nurse (RN)",
//     subTitle: "Bayada Home Care",
//     description: "Home Health Care Agency Boston, MA (Field-Based)",
//     tags: ["Full Time", "40 Hours / Week", "$75,000-$120,000"],
//     progress: 40,
//   },
//   {
//     id: 6,
//     invitation: "toApply",
//     image: <Image src={trinityHealth} alt="Career Image" />,
//     title: "Registered Nurse (RN)",
//     subTitle: "Bayada Home Care",
//     description: "Home Health Care Agency Boston, MA (Field-Based)",
//     tags: ["Full Time", "40 Hours / Week", "$75,000-$120,000"],
//     progress: 40,
//   },
// ];
// export const applicationsData = [
//   {
//     id: 1,
//     invitation: "toApply",
//     image: <Image src={trinityHealth} alt="Career Image" />,
//     title: "Registered Nurse (RN)",
//     subTitle: "Bayada Home Care",
//     description: "Home Health Care Agency Boston, MA (Field-Based)",
//     tags: ["Full Time", "40 Hours / Week", "$75,000-$120,000"],
//     progress: 80,
//   },
//   {
//     id: 2,
//     invitation: "declined",
//     image: <Image src={trinityHealth} alt="Career Image" />,
//     title: "Registered Nurse (RN)",
//     subTitle: "Bayada Home Care",
//     description: "Home Health Care Agency Boston, MA (Field-Based)",
//     tags: ["Full Time", "40 Hours / Week", "$75,000-$120,000"],
//     progress: 60,
//   },
//   {
//     id: 3,
//     invitation: "alreadyDeclined",
//     image: <Image src={trinityHealth} alt="Career Image" />,
//     title: "Registered Nurse (RN)",
//     subTitle: "Bayada Home Care",
//     description: "Home Health Care Agency Boston, MA (Field-Based)",
//     tags: ["Full Time", "40 Hours / Week", "$75,000-$120,000"],
//     progress: 40,
//   },
//   {
//     id: 4,
//     invitation: "accepted",
//     image: <Image src={trinityHealth} alt="Career Image" />,
//     title: "Registered Nurse (RN)",
//     subTitle: "Bayada Home Care",
//     description: "Home Health Care Agency Boston, MA (Field-Based)",
//     tags: ["Full Time", "40 Hours / Week", "$75,000-$120,000"],
//     progress: 40,
//   },
//   {
//     id: 5,
//     invitation: "declined",
//     image: <Image src={trinityHealth} alt="Career Image" />,
//     title: "Registered Nurse (RN)",
//     subTitle: "Bayada Home Care",
//     description: "Home Health Care Agency Boston, MA (Field-Based)",
//     tags: ["Full Time", "40 Hours / Week", "$75,000-$120,000"],
//     progress: 40,
//   },
//   {
//     id: 6,
//     invitation: "toApply",
//     image: <Image src={trinityHealth} alt="Career Image" />,
//     title: "Registered Nurse (RN)",
//     subTitle: "Bayada Home Care",
//     description: "Home Health Care Agency Boston, MA (Field-Based)",
//     tags: ["Full Time", "40 Hours / Week", "$75,000-$120,000"],
//     progress: 40,
//   },
// ];
export const jobOffersData = [
  {
    id: 1,
    image: <Image src={trinityHealth} alt="Career Image" />,
    title: "Registered Nurse (RN)",
    subTitle: "Bayada Home Care",
    description: "Home Health Care Agency Boston, MA (Field-Based)",
    tags: ["Full Time", "40 Hours / Week", "$75,000-$120,000"],
    progress: 80,
  },
  {
    id: 2,
    image: <Image src={trinityHealth} alt="Career Image" />,
    title: "Registered Nurse (RN)",
    subTitle: "Bayada Home Care",
    description: "Home Health Care Agency Boston, MA (Field-Based)",
    tags: ["Full Time", "40 Hours / Week", "$75,000-$120,000"],
    progress: 60,
  },
  {
    id: 3,
    image: <Image src={trinityHealth} alt="Career Image" />,
    title: "Registered Nurse (RN)",
    subTitle: "Bayada Home Care",
    description: "Home Health Care Agency Boston, MA (Field-Based)",
    tags: ["Full Time", "40 Hours / Week", "$75,000-$120,000"],
    progress: 40,
  },
  {
    id: 4,
    image: <Image src={trinityHealth} alt="Career Image" />,
    title: "Registered Nurse (RN)",
    subTitle: "Bayada Home Care",
    description: "Home Health Care Agency Boston, MA (Field-Based)",
    tags: ["Full Time", "40 Hours / Week", "$75,000-$120,000"],
    progress: 40,
  },
  {
    id: 5,
    image: <Image src={trinityHealth} alt="Career Image" />,
    title: "Registered Nurse (RN)",
    subTitle: "Bayada Home Care",
    description: "Home Health Care Agency Boston, MA (Field-Based)",
    tags: ["Full Time", "40 Hours / Week", "$75,000-$120,000"],
    progress: 40,
  },
  {
    id: 6,
    image: <Image src={trinityHealth} alt="Career Image" />,
    title: "Registered Nurse (RN)",
    subTitle: "Bayada Home Care",
    description: "Home Health Care Agency Boston, MA (Field-Based)",
    tags: ["Full Time", "40 Hours / Week", "$75,000-$120,000"],
    progress: 40,
  },
];

export const discoverData = [
  {
    id: 1,
    icon: <ClockIcon />,
    respondBy: "Respond by : 6/15/2024",
    status: "all",
    cardData: {
      partner: true,
      image: feature,
      heading: "Bayada Home Care",
      subHeading: "Senior Registered Nurse - Critical Care Unit",
      hospitalName: "Home Health Care Agency",
      location: "Boston, MA (Onsite)",
      tags: [
        "40 Hours/Week",
        "Rotating Shifts",
        "Full-time",
        "$75,000 - $90,000",
      ],
    },
  },
  {
    id: 2,
    icon: <ClockIcon />,
    respondBy: "Respond by : 6/15/2024",
    status: "all",
    cardData: {
      partner: false,
      image: feature,
      heading: "Bayada Home Care",
      subHeading: "Senior Registered Nurse - Critical Care Unit",
      hospitalName: "Home Health Care Agency",
      location: "Boston, MA (Onsite)",
      tags: [
        "40 Hours/Week",
        "Rotating Shifts",
        "Full-time",
        "$75,000 - $90,000",
      ],
    },
  },
  {
    id: 3,
    icon: <ClockIcon />,
    respondBy: "Respond by : 6/15/2024",
    status: "all",
    cardData: {
      partner: true,
      image: feature,
      heading: "Bayada Home Care",
      subHeading: "Senior Registered Nurse - Critical Care Unit",
      hospitalName: "Home Health Care Agency",
      location: "Boston, MA (Onsite)",
      tags: [
        "40 Hours/Week",
        "Rotating Shifts",
        "Full-time",
        "$75,000 - $90,000",
      ],
    },
  },
  {
    id: 4,
    icon: <ClockIcon />,
    respondBy: "Respond by : 6/15/2024",
    status: "all",
    cardData: {
      partner: false,
      image: feature,
      heading: "Bayada Home Care",
      subHeading: "Senior Registered Nurse - Critical Care Unit",
      hospitalName: "Home Health Care Agency",
      location: "Boston, MA (Onsite)",
      tags: [
        "40 Hours/Week",
        "Rotating Shifts",
        "Full-time",
        "$75,000 - $90,000",
      ],
    },
  },
  {
    id: 5,
    icon: <ClockIcon />,
    respondBy: "Respond by : 6/15/2024",
    status: "favorites",
    cardData: {
      partner: true,
      image: feature,
      heading: "Bayada Home Care",
      subHeading: "Senior Registered Nurse - Critical Care Unit",
      hospitalName: "Home Health Care Agency",
      location: "Boston, MA (Onsite)",
      tags: [
        "40 Hours/Week",
        "Rotating Shifts",
        "Full-time",
        "$75,000 - $90,000",
      ],
    },
  },
  {
    id: 6,
    icon: <ClockIcon />,
    respondBy: "Respond by : 6/15/2024",
    status: "favorites",
    cardData: {
      partner: false,
      image: feature,
      heading: "Bayada Home Care",
      subHeading: "Senior Registered Nurse - Critical Care Unit",
      hospitalName: "Home Health Care Agency",
      location: "Boston, MA (Onsite)",
      tags: [
        "40 Hours/Week",
        "Rotating Shifts",
        "Full-time",
        "$75,000 - $90,000",
      ],
    },
  },
  {
    id: 9,
    icon: <ClockIcon />,
    respondBy: "Respond by : 6/15/2024",
    status: "recommended",
    cardData: {
      partner: false,
      image: feature,
      heading: "Bayada Home Care",
      subHeading: "Senior Registered Nurse - Critical Care Unit",
      hospitalName: "Home Health Care Agency",
      location: "Boston, MA (Onsite)",
      tags: [
        "40 Hours/Week",
        "Rotating Shifts",
        "Full-time",
        "$75,000 - $90,000",
      ],
    },
  },
  {
    id: 10,
    icon: <ClockIcon />,
    respondBy: "Respond by : 6/15/2024",
    status: "recommended",
    cardData: {
      partner: true,
      image: feature,
      heading: "Bayada Home Care",
      subHeading: "Senior Registered Nurse - Critical Care Unit",
      hospitalName: "Home Health Care Agency",
      location: "Boston, MA (Onsite)",
      tags: [
        "40 Hours/Week",
        "Rotating Shifts",
        "Full-time",
        "$75,000 - $90,000",
      ],
    },
  },
  {
    id: 11,
    icon: <ClockIcon />,
    respondBy: "Respond by : 6/15/2024",
    status: "all",
    cardData: {
      partner: false,
      image: feature,
      heading: "Bayada Home Care",
      subHeading: "Senior Registered Nurse - Critical Care Unit",
      hospitalName: "Home Health Care Agency",
      location: "Boston, MA (Onsite)",
      tags: [
        "40 Hours/Week",
        "Rotating Shifts",
        "Full-time",
        "$75,000 - $90,000",
      ],
    },
  },
  {
    id: 12,
    icon: <ClockIcon />,
    respondBy: "Respond by : 6/15/2024",
    status: "all",
    cardData: {
      partner: false,
      image: feature,
      heading: "Bayada Home Care",
      subHeading: "Senior Registered Nurse - Critical Care Unit",
      hospitalName: "Home Health Care Agency",
      location: "Boston, MA (Onsite)",
      tags: [
        "40 Hours/Week",
        "Rotating Shifts",
        "Full-time",
        "$75,000 - $90,000",
      ],
    },
  },
  {
    id: 13,
    icon: <ClockIcon />,
    respondBy: "Respond by : 6/15/2024",
    status: "all",
    cardData: {
      partner: true,
      image: feature,
      heading: "Bayada Home Care",
      subHeading: "Senior Registered Nurse - Critical Care Unit",
      hospitalName: "Home Health Care Agency",
      location: "Boston, MA (Onsite)",
      tags: [
        "40 Hours/Week",
        "Rotating Shifts",
        "Full-time",
        "$75,000 - $90,000",
      ],
    },
  },
];
export const invitesData = [
  {
    id: 1,
    icon: <ClockIcon />,
    respondBy: "Respond by : 6/15/2024",
    cardData: {
      partner: false,
      image: feature,
      heading: "Bayada Home Care",
      subHeading: "Senior Registered Nurse - Critical Care Unit",
      hospitalName: "Home Health Care Agency",
      location: "Boston, MA (Onsite)",
      tags: [
        "40 Hours/Week",
        "Rotating Shifts",
        "Full-time",
        "$75,000 - $90,000",
      ],
    },
    status: "all",
  },
  {
    id: 2,
    icon: <ClockIcon />,
    respondBy: "Respond by : 6/15/2024",
    cardData: {
      partner: true,
      image: feature,
      heading: "Bayada Home Care",
      subHeading: "Senior Registered Nurse - Critical Care Unit",
      hospitalName: "Home Health Care Agency",
      location: "Boston, MA (Onsite)",
      tags: [
        "40 Hours/Week",
        "Rotating Shifts",
        "Full-time",
        "$75,000 - $90,000",
      ],
    },
    status: "all",
  },
  {
    id: 3,
    icon: <ClockIcon />,
    respondBy: "Respond by : 6/15/2024",
    cardData: {
      partner: true,
      image: feature,
      heading: "Bayada Home Care",
      subHeading: "Senior Registered Nurse - Critical Care Unit",
      hospitalName: "Home Health Care Agency",
      location: "Boston, MA (Onsite)",
      tags: [
        "40 Hours/Week",
        "Rotating Shifts",
        "Full-time",
        "$75,000 - $90,000",
      ],
    },
    status: "all",
  },
  {
    id: 4,
    icon: <ClockIcon />,
    respondBy: "Respond by : 6/15/2024",
    cardData: {
      partner: false,
      image: feature,
      heading: "Bayada Home Care",
      subHeading: "Senior Registered Nurse - Critical Care Unit",
      hospitalName: "Home Health Care Agency",
      location: "Boston, MA (Onsite)",
      tags: [
        "40 Hours/Week",
        "Rotating Shifts",
        "Full-time",
        "$75,000 - $90,000",
      ],
    },
    status: "all",
  },
  {
    id: 5,
    icon: <ClockIcon />,
    respondBy: "Respond by : 6/15/2024",
    cardData: {
      partner: true,
      image: feature,
      heading: "Bayada Home Care",
      subHeading: "Senior Registered Nurse - Critical Care Unit",
      hospitalName: "Home Health Care Agency",
      location: "Boston, MA (Onsite)",
      tags: [
        "40 Hours/Week",
        "Rotating Shifts",
        "Full-time",
        "$75,000 - $90,000",
      ],
    },
    status: "declined",
  },
  {
    id: 6,
    icon: <ClockIcon />,
    respondBy: "Respond by : 6/15/2024",
    cardData: {
      partner: false,
      image: feature,
      heading: "Bayada Home Care",
      subHeading: "Senior Registered Nurse - Critical Care Unit",
      hospitalName: "Home Health Care Agency",
      location: "Boston, MA (Onsite)",
      tags: [
        "40 Hours/Week",
        "Rotating Shifts",
        "Full-time",
        "$75,000 - $90,000",
      ],
    },
    status: "declined",
  },
  {
    id: 7,
    icon: <ClockIcon />,
    respondBy: "Respond by : 6/15/2024",
    cardData: {
      partner: true,
      image: feature,
      heading: "Bayada Home Care",
      subHeading: "Senior Registered Nurse - Critical Care Unit",
      hospitalName: "Home Health Care Agency",
      location: "Boston, MA (Onsite)",
      tags: [
        "40 Hours/Week",
        "Rotating Shifts",
        "Full-time",
        "$75,000 - $90,000",
      ],
    },
    status: "declined",
  },
  {
    id: 8,
    icon: <ClockIcon />,
    respondBy: "Respond by : 6/15/2024",
    cardData: {
      partner: true,
      image: feature,
      heading: "Bayada Home Care",
      subHeading: "Senior Registered Nurse - Critical Care Unit",
      hospitalName: "Home Health Care Agency",
      location: "Boston, MA (Onsite)",
      tags: [
        "40 Hours/Week",
        "Rotating Shifts",
        "Full-time",
        "$75,000 - $90,000",
      ],
    },
    status: "declined",
  },
  {
    id: 9,
    icon: <ClockIcon />,
    respondBy: "Respond by : 6/15/2024",
    cardData: {
      partner: false,
      image: feature,
      heading: "Bayada Home Care",
      subHeading: "Senior Registered Nurse - Critical Care Unit",
      hospitalName: "Home Health Care Agency",
      location: "Boston, MA (Onsite)",
      tags: [
        "40 Hours/Week",
        "Rotating Shifts",
        "Full-time",
        "$75,000 - $90,000",
      ],
    },
    status: "expired",
  },
  {
    id: 10,
    icon: <ClockIcon />,
    respondBy: "Respond by : 6/15/2024",
    cardData: {
      partner: true,
      image: feature,
      heading: "Bayada Home Care",
      subHeading: "Senior Registered Nurse - Critical Care Unit",
      hospitalName: "Home Health Care Agency",
      location: "Boston, MA (Onsite)",
      tags: [
        "40 Hours/Week",
        "Rotating Shifts",
        "Full-time",
        "$75,000 - $90,000",
      ],
    },
    status: "expired",
  },
  {
    id: 11,
    icon: <ClockIcon />,
    respondBy: "Respond by : 6/15/2024",
    cardData: {
      partner: false,
      image: feature,
      heading: "Bayada Home Care",
      subHeading: "Senior Registered Nurse - Critical Care Unit",
      hospitalName: "Home Health Care Agency",
      location: "Boston, MA (Onsite)",
      tags: [
        "40 Hours/Week",
        "Rotating Shifts",
        "Full-time",
        "$75,000 - $90,000",
      ],
    },
    status: "expired",
  },
  {
    id: 12,
    icon: <ClockIcon />,
    respondBy: "Respond by : 6/15/2024",
    cardData: {
      partner: true,
      image: feature,
      heading: "Bayada Home Care",
      subHeading: "Senior Registered Nurse - Critical Care Unit",
      hospitalName: "Home Health Care Agency",
      location: "Boston, MA (Onsite)",
      tags: [
        "40 Hours/Week",
        "Rotating Shifts",
        "Full-time",
        "$75,000 - $90,000",
      ],
    },
    status: "expired",
  },
  {
    id: 13,
    icon: <ClockIcon />,
    respondBy: "Respond by : 6/15/2024",
    cardData: {
      partner: true,
      image: feature,
      heading: "Bayada Home Care",
      subHeading: "Senior Registered Nurse - Critical Care Unit",
      hospitalName: "Home Health Care Agency",
      location: "Boston, MA (Onsite)",
      tags: [
        "40 Hours/Week",
        "Rotating Shifts",
        "Full-time",
        "$75,000 - $90,000",
      ],
    },
    status: "applied",
  },
  {
    id: 14,
    icon: <ClockIcon />,
    respondBy: "Respond by : 6/15/2024",
    cardData: {
      partner: false,
      image: feature,
      heading: "Bayada Home Care",
      subHeading: "Senior Registered Nurse - Critical Care Unit",
      hospitalName: "Home Health Care Agency",
      location: "Boston, MA (Onsite)",
      tags: [
        "40 Hours/Week",
        "Rotating Shifts",
        "Full-time",
        "$75,000 - $90,000",
      ],
    },
    status: "applied",
  },
  {
    id: 15,
    icon: <ClockIcon />,
    respondBy: "Respond by : 6/15/2024",
    cardData: {
      partner: true,
      image: feature,
      heading: "Bayada Home Care",
      subHeading: "Senior Registered Nurse - Critical Care Unit",
      hospitalName: "Home Health Care Agency",
      location: "Boston, MA (Onsite)",
      tags: [
        "40 Hours/Week",
        "Rotating Shifts",
        "Full-time",
        "$75,000 - $90,000",
      ],
    },
    status: "applied",
  },
  {
    id: 16,
    icon: <ClockIcon />,
    respondBy: "Respond by : 6/15/2024",
    cardData: {
      partner: true,
      image: feature,
      heading: "Bayada Home Care",
      subHeading: "Senior Registered Nurse - Critical Care Unit",
      hospitalName: "Home Health Care Agency",
      location: "Boston, MA (Onsite)",
      tags: [
        "40 Hours/Week",
        "Rotating Shifts",
        "Full-time",
        "$75,000 - $90,000",
      ],
    },
    status: "applied",
  },
];

export const allinvites = [
  {
    id: 1,
    icon: <ClockIcon />,
    respondBy: "Respond by : 6/15/2024",
    cardData: {
      partner: true,
      image: feature,
      heading: "Bayada Home Care",
      subHeading: "Senior Registered Nurse - Critical Care Unit",
      hospitalName: "Home Health Care Agency",
      location: "Boston, MA (Onsite)",
      tags: [
        "40 Hours/Week",
        "Rotating Shifts",
        "Full-time",
        "$75,000 - $90,000",
      ],
    },
    status: "all",
  },
  {
    id: 5,
    icon: <ClockIcon />,
    respondBy: "Respond by : 6/15/2024",
    cardData: {
      image: feature,
      partner: false,
      heading: "Bayada Home Care",
      subHeading: "Senior Registered Nurse - Critical Care Unit",
      hospitalName: "Home Health Care Agency",
      location: "Boston, MA (Onsite)",
      tags: [
        "40 Hours/Week",
        "Rotating Shifts",
        "Full-time",
        "$75,000 - $90,000",
      ],
    },
    status: "declined",
  },
  {
    id: 9,
    icon: <ClockIcon />,
    respondBy: "Respond by : 6/15/2024",
    cardData: {
      image: feature,
      partner: false,
      heading: "Bayada Home Care",
      subHeading: "Senior Registered Nurse - Critical Care Unit",
      hospitalName: "Home Health Care Agency",
      location: "Boston, MA (Onsite)",
      tags: [
        "40 Hours/Week",
        "Rotating Shifts",
        "Full-time",
        "$75,000 - $90,000",
      ],
    },
    status: "expired",
  },
  {
    id: 16,
    icon: <ClockIcon />,
    respondBy: "Respond by : 6/15/2024",
    cardData: {
      image: feature,
      partner: true,
      heading: "Bayada Home Care",
      subHeading: "Senior Registered Nurse - Critical Care Unit",
      hospitalName: "Home Health Care Agency",
      location: "Boston, MA (Onsite)",
      tags: [
        "40 Hours/Week",
        "Rotating Shifts",
        "Full-time",
        "$75,000 - $90,000",
      ],
    },
    status: "applied",
  },
];
export const applicationsData = [
  {
    id: 1,
    ticketNumber: "#60260235234",
    title: "Clinical Research Coordinator, Registered Nurse",
    title1: " Novant Health",
    title2: "Charlotte, NC",
    progress: "In Review",
    hospital: "ZH",
    idea: "idea",
    date: moment(),
    status: "review",
  },
  {
    id: 2,
    ticketNumber: "#60260235234",
    title: "Senior Registered Nurse - Critical Care Unit",
    title1: "Bayada Home Care",
    title2: "Charlotte, NC",
    progress: "resolved",
    hospital: "ZH",
    idea: "idea",
    date: moment(),
    status: "shortlisted",
  },
  {
    id: 3,
    ticketNumber: "#60260235234",
    title: "Manager, Clinical Operations",
    title1: "Providence Health Boston, MA",
    title2: "Boston, MA",
    progress: "In Review",
    hospital: "ZH",
    idea: "idea",
    date: moment(),
    status: "interviewing",
  },
  {
    id: 4,
    ticketNumber: "#60260235234",
    title: "RN, Non-Medical Home Care Nurse",
    title1: "Amada Senior Care",
    title2: "Atlanta, GA",
    progress: "In Review",
    hospital: "ZH",
    idea: "idea",
    date: moment(),
    status: "offerrecieved",
  },
  {
    id: 5,
    ticketNumber: "#60260235234",
    title: "RN, Non-Medical Home Care Nurse",
    title1: "Amada Senior Care",
    title2: "Atlanta, GA",
    progress: "In Review",
    hospital: "ZH",
    idea: "idea",
    date: moment(),
    status: "backgroundcheck",
  },
  {
    id: 6,
    ticketNumber: "#60260235234",
    title: "Field Partner Registered Nurse",
    title1: "Life Guard Insurance",
    title2: "Miami, FL",
    progress: "In Review",
    hospital: "ZH",
    idea: "idea",
    date: moment(),
    status: "hired",
  },
  {
    id: 7,
    ticketNumber: "#60260235234",
    title: "Ambulatory Surgery Center Nurse",
    title1: "OrthoCarolina",
    title2: "Raleigh, NC",
    progress: "In Review",
    hospital: "ZH",
    idea: "idea",
    date: moment(),
    status: "archived",
  },
  {
    id: 8,
    ticketNumber: "#60260235234",
    title: "Oncology Clinical Services Navigator",
    title1: "NP Atrium Health",
    title2: "Durham, NC",
    progress: "In Review",
    hospital: "ZH",
    idea: "idea",
    date: moment(),
    status: "withdrawn",
  },
  {
    id: 9,
    ticketNumber: "#60260235234",
    title: "Registered Nurse (RN) Supervisor",
    title1: "Carolina Case Management",
    title2: "Charleston, SC",
    progress: "In Review",
    hospital: "ZH",
    idea: "idea",
    date: moment(),
    status: "declined",
  },
  {
    id: 10,
    ticketNumber: "#60260235234",
    title: "Diabetes Education Specialist",
    title1: "Novant Health",
    title2: "Winston-Salem, NC",
    progress: "In Review",
    hospital: "ZH",
    idea: "idea",
    date: moment(),
    status: "shortlisted",
  },
];
