import feature from "../../../public/images/feature.png";

export const employersData = [
  {
    id: 1,
    image: feature,
    title: "Registered Nurse (RN)",
    partner: true,
    employerType: "Home Health Agency",
    employerSize: "10000+ Employees",
    location: "Charlotte, NC",
    description:
      "Morem ipsum dolor sit amet, consectetur adipiscing elit. Nunc vulputate libero et velit interdum, ac aliquet odio mattis. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos.Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himen...",
    jobs: 10,
    status: "favorites",
  },
  {
    id: 2,
    image: feature,
    title: "Registered Nurse (RN)",
    partner: false,
    employerType: "Home Health Agency",
    employerSize: "10000+ Employees",
    location: "Charlotte, NC",
    description:
      "Morem ipsum dolor sit amet, consectetur adipiscing elit. Nunc vulputate libero et velit interdum, ac aliquet odio mattis. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos.Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himen...",
    jobs: 10,
    status: "favorites",
  },
  {
    id: 3,
    image: feature,
    title: "Registered Nurse (RN)",
    partner: false,
    employerType: "Home Health Agency",
    employerSize: "10000+ Employees",
    location: "Charlotte, NC",
    description:
      "Morem ipsum dolor sit amet, consectetur adipiscing elit. Nunc vulputate libero et velit interdum, ac aliquet odio mattis. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos.Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himen...",
    jobs: 10,
    status: "favorites",
  },
  {
    id: 4,
    image: feature,
    title: "Registered Nurse (RN)",
    partner: true,
    employerType: "Home Health Agency",
    employerSize: "10000+ Employees",
    location: "Charlotte, NC",
    description:
      "Morem ipsum dolor sit amet, consectetur adipiscing elit. Nunc vulputate libero et velit interdum, ac aliquet odio mattis. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos.Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himen...",
    jobs: 10,
    status: "recommended",
  },
  {
    id: 5,
    image: feature,
    title: "Registered Nurse (RN)",
    partner: true,
    employerType: "Home Health Agency",
    employerSize: "10000+ Employees",
    location: "Charlotte, NC",
    description:
      "Morem ipsum dolor sit amet, consectetur adipiscing elit. Nunc vulputate libero et velit interdum, ac aliquet odio mattis. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos.Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himen...",
    jobs: 10,
    status: "recommended",
  },
  {
    id: 6,
    image: feature,
    title: "Registered Nurse (RN)",
    partner: true,
    employerType: "Home Health Agency",
    employerSize: "10000+ Employees",
    location: "Charlotte, NC",
    description:
      "Morem ipsum dolor sit amet, consectetur adipiscing elit. Nunc vulputate libero et velit interdum, ac aliquet odio mattis. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos.Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himen...",
    jobs: 10,
    status: "favorites",
  },
  {
    id: 7,
    image: feature,
    title: "Registered Nurse (RN)",
    partner: false,
    employerType: "Home Health Agency",
    employerSize: "10000+ Employees",
    location: "Charlotte, NC",
    description:
      "Morem ipsum dolor sit amet, consectetur adipiscing elit. Nunc vulputate libero et velit interdum, ac aliquet odio mattis. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos.Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himen...",
    jobs: 10,
    status: "all",
  },
  {
    id: 8,
    image: feature,
    title: "Registered Nurse (RN)",
    partner: true,
    employerType: "Home Health Agency",
    employerSize: "10000+ Employees",
    location: "Charlotte, NC",
    description:
      "Morem ipsum dolor sit amet, consectetur adipiscing elit. Nunc vulputate libero et velit interdum, ac aliquet odio mattis. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos.Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himen...",
    jobs: 10,
    status: "recommended",
  },
  {
    id: 9,
    image: feature,
    title: "Registered Nurse (RN)",
    partner: true,
    employerType: "Home Health Agency",
    employerSize: "10000+ Employees",
    location: "Charlotte, NC",
    description:
      "Morem ipsum dolor sit amet, consectetur adipiscing elit. Nunc vulputate libero et velit interdum, ac aliquet odio mattis. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos.Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himen...",
    jobs: 10,
    status: "all",
  },
  {
    id: 10,
    image: feature,
    title: "Registered Nurse (RN)",
    partner: true,
    employerType: "Home Health Agency",
    employerSize: "10000+ Employees",
    location: "Charlotte, NC",
    description:
      "Morem ipsum dolor sit amet, consectetur adipiscing elit. Nunc vulputate libero et velit interdum, ac aliquet odio mattis. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos.Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himen...",
    jobs: 10,
    status: "all",
  },
];
